### ISSUE TITLE
[NFR] Add telegram support

### ISSUE THREAD

**Issue by williamokano** [haskellcamargo/gemidao-do-zap#10]
Se foder com inglês, aqui é Brasil jorra!

Adicionar suporte ao telegram nessa caralha que vai ficar ducaralho

**Comment by iagocaldeira** [comment]
Telegram agora aceita ligação né?

**Comment by cuchi** [comment]
[Aceita sim!](https://core.telegram.org/method/auth.sendCall) Mas pelo visto não há maneiras de mandar diretamente:
https://core.telegram.org/api

**Comment by Synk0** [comment]
Recomendo usarem essa api [pwrtelegram.xyz](pwrtelegram.xyz)
