### ISSUE TITLE
Foto do povo brasileiro no README

### ISSUE THREAD

**Issue by JoaoGFarias** [haskellcamargo/gemidao-do-zap#12]
Por quê não?
PR https://github.com/haskellcamargo/gemidao-do-zap/pull/13
![6096234_700b](https://user-images.githubusercontent.com/1585655/29083653-d40bb660-7c3f-11e7-896c-efd243f32918.jpg)

**Comment by haskellcamargo** [comment]
# PERFEITO!

Manda um PR pa nois!
