### ISSUE TITLE
Erro ao instalar

### ISSUE THREAD

**Issue by williamokano** [haskellcamargo/gemidao-do-zap#15]
Estou recebendo o seguinte erro ao instalar:

```
npm ERR! path /usr/local/lib/node_modules/gemidao-do-zap/dist/cli.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/local/lib/node_modules/gemidao-do-zap/dist/cli.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/william/.npm/_logs/2017-08-08T17_31_32_441Z-debug.log
```

Ideias?

**Comment by haskellcamargo** [comment]
Instalou como `sudo`?

**Comment by williamokano** [comment]
Sim sinhô

**Comment by haskellcamargo** [comment]
Isso costuma ser erro do `npm`. Tente rodar `sudo npm cache clean` e então tente novamente.

**Comment by williamokano** [comment]
![image](https://user-images.githubusercontent.com/5909442/29085728-940e9080-7c46-11e7-8f3e-912febaee9a5.png)

**Comment by williamokano** [comment]
Não, o erro persiste mesmo após o cache clean

**@edit**
Pensei que fosse erro do fish, mas no bash da mesma zica.

Essa pasta `/usr/local/bin/node_modules` nem existe no meu pc uhASUEHASuhe

**Comment by williamokano** [comment]
@haskellcamargo Resolvido. Apaguei o symlink do gemidao do zap na pasta /usr/local/lib/node_modules, limpei cache npm e reinstalei foi sucesso
