### ISSUE TITLE
Human Explanation in English

### ISSUE THREAD

**Issue by imerkle** [haskellcamargo/gemidao-do-zap#20]
Google says 

```
For example, I can send the whining of the zap to my friend by simulating a call from his mother, and when he answers, AAAWN OOOWN NHAAA AWWWWN AAAAAH (inclusive, you just fell on the zap of written zap).
```
I didnt understand really.

**Comment by williamokano** [comment]
In Brazil there's a big hype now about the "gemidão do zap", which is a prank where you send fake videos with the sound of a pornstar moaning, extremely loud.

Nowadays, the "gemidão do zap" can be disguised in almost everything, videos, songs, phone calls, etc.

The "gemidão do zap" audio is inside the resource folder, but I strongly advise you to not open if not alone, NSFW just to know.

The purpose of this project is to make phone calls with fake "callers" (you can fake the caller number), like for example, put someone's mom phone number, and call him with the "gemidão do zap".

By "gemidão", the translation should be something like "a loud sex moaning". I just don't know how to say that (formal nor slang).

**Comment by bergamin** [comment]
@dsslimshaddy, think of a NSFW Rick Roll audio. This thing is everywhere. It is just exactly the same prank mechanics of Rick Roll, but Brazilian level

**Comment by JoaoGFarias** [comment]
![6096234_700b](https://user-images.githubusercontent.com/1585655/29100036-674375a0-7c7f-11e7-9c51-d206d0690de3.jpg)

**Comment by yannbf** [comment]
I'm just gonna leave this here:
https://www.youtube.com/watch?v=peNTqOo9Qf0

**Comment by vmarchesin** [comment]
Just to clarify, "gemido" should be translated as "moaning" and not "whining". "Gemidão do zap" should be translated as "whatsapp's moaning", since "zap" is not a slang that people would understand outside Brazil.
