### ISSUE TITLE
[NFR] Provider de comunicação

### ISSUE THREAD

**Issue by walteraa** [haskellcamargo/gemidao-do-zap#29]
Não sei se já existe alguma issue/PR pra isso, mas poderiamos usar a ideia de providers isolados, isso faria com que pudessemos utilizar qualquer provedor existente e adicionarmos novos provedores.

Outra coisa que poderíamos fazer é desacoplar o áudio, poderíamos usar outros áudios de zoeira(e. g.: o "7 dias" da Samara do filme *O chamado*), mas não sei se descaracterizaria a coisa.

**Comment by williamokano** [comment]
Sobre os providers eu iria fazer, eu concordo que seja separado, não curti
o PR que implementa o direct all.

Sobre mudar o áudio, até gosto da ideia, mas meio que descaracteriza a main
idea do projeto, mas o @haskellcamargo que é dono, ele que sabe qual o rumo
rsrs

Em 9 de ago de 2017 2:15 PM, "Walter Alves" <notifications@github.com>
escreveu:

**Comment by williamokano** [comment]
Duplicadas deste PR #25 e destes issue #6 #11

**Comment by walteraa** [comment]
Show!!
