### ISSUE TITLE
Conta TotalVoice sem crédito

### ISSUE THREAD

**Issue by ghost** [haskellcamargo/gemidao-do-zap#3]
Minha conta no TotalVoice veio sem nenhum crédito, como resolver?

**Comment by haskellcamargo** [comment]
Ao que parece, nem todas as contas criadas estão vindo com créditos de demonstração. :cry: 
Ainda não sei como resolver (dentro da legalidade).

**Comment by arthurmiksza** [comment]
como faz pra colocar crédito la entao? huehsheauaehuhae

**Comment by marcelinhov2** [comment]
@arthurmiksza eu colocaria tranquilamente também hahahahaha

**Comment by haskellcamargo** [comment]
O próprio portal deles oferece uma seção para recarga, se alguém se interessar a levar a zoeira a esse nível haha

**Comment by marcelinhov2** [comment]
@haskellcamargo não funciona a sessão de recarga

**Comment by haskellcamargo** [comment]
Estranho. Utilizo, empresarialmente, o plano pago deles e atende bem, inclusive a recarga funciona normalmente. Devem estar passando por alguma instabilidade pelo excesso de usuários.

**Comment by jeftarmascarenhas** [comment]
O TotalVoice, ta zuado.

**Comment by yeltsinxyz** [comment]
@marcelinhov2 Vê se por aqui vai: http://evoline.freshdesk.com/support/solutions/articles/17000027698-como-fazer-uma-recarga-via-boleto

EDIT: Apesar que aqui também não está aparecendo rs

**Comment by marcelinhov2** [comment]
Esse botão nem aparece pra mim @yeltsinseal  =/

**Comment by ghost** [comment]
@yeltsinseal pra mim tb n!

**Comment by OtacilioN** [comment]
Velhoooo, como assim eu tava muito empolgado com essa trollagem, ai Meu Deus, vamos lá mitos, achem um novo serviço de ligação com créditos de testes ou que a função de recarga funcione.

**Comment by MaikeMota** [comment]
Senhores, recarreguem por aqui e sejam felizes! MELHOR PROGRAMA EVER!

https://api.evoline.com.br/recarga/recarga-action.php

**Comment by OtacilioN** [comment]
Galera, é só esperar um tempinho que os 3 reais entra, divirtam-se!

**Comment by MaikeMota** [comment]
O @OtacilioN tem razão, demora mas cai! Cuidado ao colocar crédito antes de receber o bônus pois eles vão setar seu créditos como R$ 3 e você vai perder seus créditos!

**Comment by igor9silva** [comment]
Botei R$50,00. Melhor investimento da minha vida.

**Comment by danielmadu** [comment]
Eu acho que a totalvoice ta barrando os créditos gratuitos, tô com um token com crédito de testes ainda (suficientes para fazer a ligação) e está pedindo para fazer recarga :confused:

**Comment by rafaelcavalcante** [comment]
**ATENÇÃO**

Os créditos podem demorar pra cair. Comigo demorou 12 horas.

**Comment by rafaelcavalcante** [comment]
@haskellcamargo fecha essa issue, pfv
