### ISSUE TITLE
Falha na instalação 

### ISSUE THREAD

**Issue by hiltonkBR** [haskellcamargo/gemidao-do-zap#31]
Esta retornando isso quando rodo o npm:

npm WARN engine superagent@3.5.2: wanted: {"node":">= 0.12"} (current: {"node":"                                                                                        0.10.29","npm":"1.4.21"})
npm WARN engine camelcase@4.1.0: wanted: {"node":">=4"} (current: {"node":"0.10.                                                                                        29","npm":"1.4.21"})
npm WARN engine os-locale@2.1.0: wanted: {"node":">=4"} (current: {"node":"0.10.                                                                                        29","npm":"1.4.21"})
npm WARN engine read-pkg-up@2.0.0: wanted: {"node":">=4"} (current: {"node":"0.1                                                                                        0.29","npm":"1.4.21"})
npm WARN engine string-width@2.1.1: wanted: {"node":">=4"} (current: {"node":"0.                                                                                        10.29","npm":"1.4.21"})
npm WARN engine form-data@2.2.0: wanted: {"node":">= 0.12"} (current: {"node":"0                                                                                        .10.29","npm":"1.4.21"})
npm WARN engine find-up@2.1.0: wanted: {"node":">=4"} (current: {"node":"0.10.29                                                                                        ","npm":"1.4.21"})
npm WARN engine read-pkg@2.0.0: wanted: {"node":">=4"} (current: {"node":"0.10.2                                                                                        9","npm":"1.4.21"})
npm WARN engine is-fullwidth-code-point@2.0.0: wanted: {"node":">=4"} (current:                                                                                         {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine strip-ansi@4.0.0: wanted: {"node":">=4"} (current: {"node":"0.10                                                                                        .29","npm":"1.4.21"})
npm WARN engine execa@0.7.0: wanted: {"node":">=4"} (current: {"node":"0.10.29",                                                                                        "npm":"1.4.21"})
npm WARN engine mem@1.1.0: wanted: {"node":">=4"} (current: {"node":"0.10.29","n                                                                                        pm":"1.4.21"})
npm WARN engine ansi-regex@3.0.0: wanted: {"node":">=4"} (current: {"node":"0.10                                                                                        .29","npm":"1.4.21"})
npm WARN engine locate-path@2.0.0: wanted: {"node":">=4"} (current: {"node":"0.1                                                                                        0.29","npm":"1.4.21"})
npm WARN engine mimic-fn@1.1.0: wanted: {"node":">=4"} (current: {"node":"0.10.2                                                                                        9","npm":"1.4.21"})
npm WARN engine load-json-file@2.0.0: wanted: {"node":">=4"} (current: {"node":"                                                                                        0.10.29","npm":"1.4.21"})
npm WARN engine path-type@2.0.0: wanted: {"node":">=4"} (current: {"node":"0.10.                                                                                        29","npm":"1.4.21"})
npm WARN engine npm-run-path@2.0.2: wanted: {"node":">=4"} (current: {"node":"0.                                                                                        10.29","npm":"1.4.21"})
npm WARN engine p-finally@1.0.0: wanted: {"node":">=4"} (current: {"node":"0.10.                                                                                        29","npm":"1.4.21"})
npm WARN engine get-stream@3.0.0: wanted: {"node":">=4"} (current: {"node":"0.10                                                                                        .29","npm":"1.4.21"})
npm WARN engine p-locate@2.0.0: wanted: {"node":">=4"} (current: {"node":"0.10.2                                                                                        9","npm":"1.4.21"})
npm WARN engine path-exists@3.0.0: wanted: {"node":">=4"} (current: {"node":"0.1                                                                                        0.29","npm":"1.4.21"})
npm WARN engine strip-bom@3.0.0: wanted: {"node":">=4"} (current: {"node":"0.10.                                                                                        29","npm":"1.4.21"})
npm WARN engine path-key@2.0.1: wanted: {"node":">=4"} (current: {"node":"0.10.2                                                                                        9","npm":"1.4.21"})
npm WARN engine p-limit@1.1.0: wanted: {"node":">=4"} (current: {"node":"0.10.29","npm":"1.4.21"})
/usr/local/bin/gemidao-do-zap -> /usr/local/lib/node_modules/gemidao-do-zap/dist/cli.js
gemidao-do-zap@0.1.2 /usr/local/lib/node_modules/gemidao-do-zap
├── superagent-promise@1.1.0
├── colors@1.1.2
├── bluebird@3.5.0
├── superagent@3.5.2 (methods@1.1.2, component-emitter@1.2.1, cookiejar@2.1.1, extend@3.0.1, mime@1.3.6, formidable@1.1.1, qs@6.5.0, debug@2.6.8, readable-stream@2.3.3, form-data@2.2.0)
├── ramda@0.24.1
└── yargs@8.0.2 (get-caller-file@1.0.2, decamelize@1.2.0, camelcase@4.1.0, set-blocking@2.0.0, which-module@2.0.0, y18n@3.2.1, require-main-filename@1.0.1, require-directory@2.1.1, yargs-parser@7.0.0, string-width@2.1.1, cliui@3.2.0, os-locale@2.1.0, read-pkg-up@2.0.0)

**Comment by igor9silva** [comment]
Qual versão do node? Precisa ser 6+

**Comment by williamokano** [comment]
Atualize o node

**Comment by wellavelino** [comment]
` wanted: {"node":">= 0.12"} (current: {"node":" 0.10.29","npm":"1.4.21"})`

Atualiza seu node

**Comment by hiltonkBR** [comment]
Deu certo doutores, valeu!
