### ISSUE TITLE
como eu uso

### ISSUE THREAD

**Issue by dandeiro** [haskellcamargo/gemidao-do-zap#33]
gente, sou leigo nesse assunto, queria saber como que eu faço isso, eu ja baixei o Nodejs 8.12, mas n sei o que eu tenho que fazer

**Comment by williamokano** [comment]
sudo npm install -g gemidao-do-zap

Depois roda no terminal confirme instruções

gemidao-do-zap --token=banana --de=267182 --para=1672828

O token tu tem que cadastrar no site, só seguir o link do readme

Em 9 de ago de 2017 6:28 PM, "dandeiro" <notifications@github.com> escreveu:

**Comment by dandeiro** [comment]
mas onde eu escrevo isso? esse codigo ai sudo...

**Comment by williamokano** [comment]
Terminal do Linux se for Linux, senão no powershell do Windows sem sudo

Em 9 de ago de 2017 6:45 PM, "dandeiro" <notifications@github.com> escreveu:

**Comment by dandeiro** [comment]
valeu amigo, consegui
