### ISSUE TITLE
Ligação caindo na caixa postal

### ISSUE THREAD

**Issue by flavioribeirojr** [haskellcamargo/gemidao-do-zap#35]
Quando a vítima não cai no gemidão a mensagem cai na caixa postal e acaba consumindo os créditos do total voice

**Comment by williamokano** [comment]
Tipo uma ligação telefônica comum?

**Comment by flavioribeirojr** [comment]
Sim, acho que se a pessoa atender à ligação vai ouvir o gemidão. Até que se, parando pra pensar, é uma boa sacada kkkk

**Comment by CesarSantosBR** [comment]
O @flavio-jr  está correto.

Meu primeiro teste foi com um colega do trabalho. pedi para ele não atender e assim não consumir créditos. Com isso, a ligação caiu na caixa postal e quando o mesmo foi conferir, era o gemidão.

**Comment by williamokano** [comment]
Ligações não atendidas vão para a caixa postal mesmo.
