### ISSUE TITLE
Número de telefone inválido

### ISSUE THREAD

**Issue by devmeireles** [haskellcamargo/gemidao-do-zap#41]
Número de telefone inválido
Alguém com o mesmo problema?

**Comment by haskellcamargo** [comment]
Como você está colocando o número? O formato é `DDD` + `9`? + `NUMERO`

**Comment by williamokano** [comment]
Você está colocando sem o +55 e no formato DDD + NUMERO?

**Comment by devmeireles** [comment]
DDD9NUMERO, tipo 119xxxxxxxx

**Comment by guilhermelirio** [comment]
Uma dica: Telefone fixo cobra apenas R$ 0,06 centavos.
