### ISSUE TITLE
Delay no som

### ISSUE THREAD

**Issue by PabloPG** [haskellcamargo/gemidao-do-zap#44]
@haskellcamargo 
Acho que seria interessante adicionar um audio com delay de 2s para começar o gemido.

**Comment by haskellcamargo** [comment]
Ele já tem um delay da rede por padrão. Se adicionar isso, gente com sinal ruim nem vai ouvir mais o gemidão.

**Comment by PabloPG** [comment]
Entendi, é porque sacaniei alguns amigos do setor e percebi que logo quando atendia o telefone e antes de chegar com ele no ouvido já começava o som.

Mas deve depender de região para região.
