### ISSUE TITLE
Mudar áudio

### ISSUE THREAD

**Issue by ezosk** [haskellcamargo/gemidao-do-zap#51]
Então, minha pergunta é bem simples. Tentei olhar no código, trocar a url de áudio, trocar o arquivo, mas não consigo mudar o áudio que é "proferido" quando a pessoa atende.
Tem como fazer isso com base nesse código?
Peço perdão pela simplicidade da dúvida, mas não sou programador. Obrigado desde já.

**Comment by williamokano** [comment]
Sim, só trocar o parâmetro aqui
https://github.com/haskellcamargo/gemidao-do-zap/blob/master/src/gemidao.js#L25

Em 10 de ago de 2017 9:32 PM, "ezosk" <notifications@github.com> escreveu:

**Comment by ezosk** [comment]
Além do github, existe algum outro lugar em que eu possa upar o áudio que eu quero de forma com q ele seja lido corretamente?

**Comment by williamokano** [comment]
Qualquer lugar público, não vem vem nenhum a mente agora.

Em 10 de ago de 2017 9:41 PM, "ezosk" <notifications@github.com> escreveu:

**Comment by castroalves** [comment]
Coloque o MP3 na pasta public do Dropbox, pegue o link e coloque como parâmetro.
