### ISSUE TITLE
O script só utiliza conta trial?

### ISSUE THREAD

**Issue by shrimpgo** [haskellcamargo/gemidao-do-zap#57]
Olá! A minha zoeira foi tão longe q comprei créditos para zoar os amiguinhos, porém o script está acusando q a minha conta é trial e que só poderia usar o número q cadastrei no site totalvoice. Ae fui lá, confirmei meu e-mail, completei meu cadastro e mudei meu número q havia cadastrado, mas mesmo assim o script continua acusando q a minha conta é trial. O que tá rolando? Vejo q o problema não é do totalvoice. A mensagem que aparece para mim é essa:

✗ Erro: Numero nao permitido durante o trial. Use o ddd9xxxxxxxx ou Ative seu Cadastro em http://api.totalvoice.com.br/painel .

**Comment by athosmoreno** [comment]
#58 #54 #56
