### ISSUE TITLE
Número destino não permitido.

### ISSUE THREAD

**Issue by wviana** [haskellcamargo/gemidao-do-zap#62]
Pessoal, estou recebendo esas mensagem.

`Número destino não permitido. Cadastre os numeros em https://api.totalvoice.com.br/painel em Minha Conta` 

Mandando o para o meu próprio número deu certo, para o dos outros não.

Alguma dica?

**Comment by GabrielCoelho** [comment]
É que a API do totalvoice... ou melhor, o totalvoice em si não permite mais ligações para números que não sejam previamente cadastrados.

Então a zueira, infelizmente, está com um "fim"

**Comment by wviana** [comment]
Sim,

Obrigado pelo retorno.
Mesmo assim consegui convencer vários amigos a me passarem o token.

Deu para me divertir bastante.

**Comment by sayhicoelho** [comment]
A zoeira não pode acabar!!!
