### ISSUE TITLE
Tradução

### ISSUE THREAD

**Issue by giovannism20** [haskellcamargo/gemidao-do-zap#7]
A zoeira não pode terminar aqui, porque somos brasileiros </br>, portanto abro está issue para tradução do projeto e evolução ao nível gringo !!!!! :octocat: :1st_place_medal:

**Comment by JoaoGFarias** [comment]
Parece que o código todo já está em inglês, confere?
Falta só os docs?

**Comment by igor9silva** [comment]
+1

**Comment by igor9silva** [comment]
@JoaoGFarias só funciona com números do Brasil.

**Comment by iagocaldeira** [comment]
na issue #20 tem um pedido para fazer a tradução tambem do readme e do meme em si

**Comment by williamokano** [comment]
Alguém conhece uma api pra international call?

**Comment by iagocaldeira** [comment]
twilio é a mais famosa

**Comment by walteraa** [comment]
@igor9silva podemos evoluir pra usar outros provedores de chamada, isso liberaria a limitação nacional. Inclusive já existe um esforço pra isso, salvo engano um PR já foi merged referente a outro provedor.

**Comment by igor9silva** [comment]
O @jamcarlos deu a ideia de conectar com o Skype também. Se não me engano tem API pra isso.
